### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by seongbin9786** [classvar/classvar-record-backend#1]
8월 16/17일 TODOLIST

- [ ] WebSocket 기반 Signaling Server 생성하기 (당장은 서버에서 해당 연결의 state를 추적하지 않는다. 일단 skip)
- [ ] 채팅은 아직 UI가 없으니까 구현하지 않기
- [ ] coturn을 어떻게 호스팅할지 결정하기 (트래픽이 크고, up/down이 심할텐데)
- [ ] 녹화서버에서 Spring Session에 접근할 일이 있을까? 그냥 connectionStateChange만 수행해도 충분하다
- [ ] 녹화서버의 sticky가 끊긴 경우, 녹화가 끊긴 경우의 fallback 및 영상 병합 기준 마련하기
- [ ] 녹화서버 사용자별 식별자 정의하기. 응시자의 경우 단일 식별자가 없지? 이러면  프론트에서 녹화 서버와 연결을 맺을 때 { courseId, examId, userId } 까지 제공해야 한다. (courseId, userId)가 응시자 식별자이고, examId는 같은 코스에서 시험을 식별하기 위함이다.
